In [1]:
import pandas as pd
import os
import time
import glob

In [4]:
count = 0
data = []
start = time.time()
for file in glob.glob('Data/Stocks/*.txt'):
    if(os.stat(file).st_size != 0): # if the file is NOT empty
        tempdf = pd.read_csv(file)
        tempdf['Stock'] = str.upper(file[12:-7:1]) # Stock Name
        tempdf = tempdf[['Date','Open','High','Low','Close','Volume','Stock']] # we keep the columns that we want 
        data.append(tempdf)        
    count += 1
    if count%1000 == 0:
        print('Progress:',count,'/ 7195 = ',int(100*count/7195),'%  Time = ', int(time.time() - start)//60,'min')  
print(count)
data = pd.concat(data)
data.reset_index(inplace=True, drop=True)

Progress: 1000 / 7195 =  13 %  Time =  0 min
Progress: 2000 / 7195 =  27 %  Time =  0 min
Progress: 3000 / 7195 =  41 %  Time =  0 min
Progress: 4000 / 7195 =  55 %  Time =  0 min
Progress: 5000 / 7195 =  69 %  Time =  1 min
Progress: 6000 / 7195 =  83 %  Time =  1 min
Progress: 7000 / 7195 =  97 %  Time =  1 min
7195

In [5]:
# print(data)
df = data.sort_values(by=['Date'], axis=0)

In [14]:
df.reset_index(inplace=True, drop=True)
df.head(30)

          Date    Open    High     Low   Close   Volume Stock
0   1962-01-02  0.6277  0.6362  0.6201  0.6201  2575579    GE
1   1962-01-02  6.4130  6.4130  6.3378  6.3378   467056   IBM
2   1962-01-03  6.3378  6.3963  6.3378  6.3963   350294   IBM
3   1962-01-03  0.6201  0.6201  0.6122  0.6201  1764749    GE
4   1962-01-04  0.6201  0.6201  0.6037  0.6122  2194010    GE
5   1962-01-04  6.3963  6.3963  6.3295  6.3295   314365   IBM
6   1962-01-05  0.6122  0.6122  0.5798  0.5957  3255244    GE
7   1962-01-05  6.3211  6.3211  6.1958  6.2041   440112   IBM
8   1962-01-08  0.5957  0.5957  0.5716  0.5957  3696430    GE
9   1962-01-08  6.2041  6.2041  6.0373  6.0870   655676   IBM
10  1962-01-09  0.5957  0.6037  0.5878  0.5957  2778285    GE
11  1962-01-09  6.1208  6.2376  6.1208  6.1621   592806   IBM
12  1962-01-10  0.5957  0.6037  0.5957  0.5957  2337096    GE
13  1962-01-10  6.1707  6.2041  6.1707  6.1707   359274   IBM
14  1962-01-11  6.1875  6.2376  6.1875  6.2376   386220   IBM
15  1962-01-11  0.5957  0.5957  0.5878  0.5957  1943605    GE
16  1962-01-12  0.5957  0.6037  0.5878  0.5878  2015151    GE
17  1962-01-12  6.2543  6.2962  6.2543  6.2543   529933   IBM
18  1962-01-15  0.5957  0.5957  0.5957  0.5957  2527879    GE
19  1962-01-15  6.2708  6.2962  6.2708  6.2792   305383   IBM
20  1962-01-16  6.2708  6.2708  6.2128  6.2128   305383   IBM
21  1962-01-16  0.5957  0.6037  0.5957  0.6037  1657434    GE
22  1962-01-17  0.6037  0.6037  0.5878  0.5878  2551729    GE
23  1962-01-17  6.1875  6.1875  6.0956  6.1125   502984   IBM
24  1962-01-18  6.1291  6.1875  6.1291  6.1291   449093   IBM
25  1962-01-18  0.5878  0.5957  0.5878  0.5957  1764749    GE
26  1962-01-19  6.1291  6.1457  6.0624  6.1374   485021   IBM
27  1962-01-19  0.5957  0.6037  0.5957  0.6037  1585893    GE
28  1962-01-22  0.6037  0.6122  0.6037  0.6037  1693206    GE
29  1962-01-22  6.1374  6.1958  6.1208  6.1208   332329   IBM

In [15]:
df.to_csv('sortedDFwithVol.csv')